project_id = "eadjoqlyjxwqjfvukvqx"

[[functions]]
name = "integration-dispatcher"
verify_jwt = false

[[functions]]
name = "dead-reporter"
verify_jwt = false

[[cron.jobs]]
name = "integration-dispatcher"
schedule = "*/2 * * * *"
endpoint = "/functions/v1/integration-dispatcher"

[[cron.jobs]]
name = "dead-reporter-daily"
schedule = "0 6 * * *"
endpoint = "/functions/v1/dead-reporter"